### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by usedbytes** [adafruit/Adafruit_OV7670#14]
Could you provide details of the license the code in this repo is published under?

Some of the files have explicit MIT headers, but some don't and there's no repo-level LICENSE file. Specifically I'm interested in using the low-level `ov7670.{c,h}` register settings in my project.

Thanks!

**Comment by PaintYourDragon** [comment]
Added LICENSE file and SPDX headers throughout. All MIT, knock yourself out, thank you for asking!
